spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  profiles:
    active: local

# JdbcTemplate sql log
logging:
  level:
    org:
      springframework: jdbc=debug