spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/kotlin
        driver-class-name: org.mariadb.jdbc.Driver
        username: root
        password: ghdcoalss33
    profiles:
        active: local